In [1]:
%pylab
%matplotlib inline

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
import numpy as np

In [4]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print(arr1)

[ 6.   7.5  8.   0.   1. ]


In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [6]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim

2

In [8]:
arr2.shape

(2, 4)

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
np.empty((2,3,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [13]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr1.dtype

dtype('float64')

In [19]:
arr2 = np.array([1,2,3],dtype = np.int32)
arr2.dtype

dtype('int32')

In [21]:
arr2.astype(np.float64).dtype

dtype('float64')

In [22]:
arr = np.array([3.7,-1.2,-2.7])
arr.astype(np.int32)

array([ 3, -1, -2])

In [29]:
num_str = np.array(['1.24','4.55','-1.1'],dtype=np.string_)
num_str.astype(float).dtype

dtype('float64')

In [31]:
int_array = np.arange(10)
calibers = np.array([.22,.4444,.7777],dtype = np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [32]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [34]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [36]:
arr**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])