In [2]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [3]:
def add(x,y):
    return x+y

z = (2,3)
print(add(*z)) #必须加上星号

5


In [4]:
def add(x,y):
    return x+y

w = {'x':2, 'y':3}
print(add(**w)) #必须加上星号

5


In [5]:
def sqr(x):
    return x**2
a = [2,3,4]
print(list(map(sqr,a)))

[4, 9, 16]


In [6]:
a = (2,3,4)
b = [10,5,3]
print(list(map(add,a,b)))

[12, 8, 7]


In [8]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [9]:
vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [10]:
hstack((x,y))

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [11]:
dstack((x,y))

array([[[ 0, 50],
        [ 1, 51],
        [ 2, 52]],

       [[10, 60],
        [11, 61],
        [12, 62]]])

In [12]:
z = array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])