In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a.reshape(3,2) # created a new array

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
a.reshape(4,2)

ValueError: total size of new array must be unchanged

In [7]:
a = arange(3)
shape(a)

(3,)

In [9]:
y = a[newaxis,:]
shape(y)

(1, 3)

In [12]:
y = a[:,newaxis]
shape(y)

(3, 1)

In [14]:
y = a[newaxis,newaxis,:]
shape(y)

(1, 1, 3)

In [17]:
a = arange(6)
a.shape = (2,1,3)

In [19]:
b = a.squeeze()
# squeeze 返回一个将所有长度为1的维度去除的新数组
b.shape

(2, 3)

In [20]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [22]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [23]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [24]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [25]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [26]:
b = a.T
b.shape

(5, 4, 3)

In [27]:
a = arange(6)
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
b = a.T
b[0,1] = 30
b

array([[ 0, 30],
       [ 1,  4],
       [ 2,  5]])

In [29]:
#转置返回的是对原数组的另一种view，所以改变转置会改变原来数组的值。
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [30]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [31]:
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [32]:
z.shape

(4, 3)

In [34]:
z = concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [35]:
z.shape

(2, 6)

In [36]:
vstack((x,y)).shape

(4, 3)

In [37]:
hstack((x,y)).shape

(2, 6)

In [38]:
dstack((x,y)).shape

(2, 3, 2)

In [39]:
a = array([[0,1],
            [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [40]:
b[0] = 10
print(b)
print(a)

[10  1  2  3]
[[0 1]
 [2 3]]


In [41]:
a.flat

In [42]:
b = a.flat

In [43]:
b[0]

0

In [44]:
b[0] = 10
print(a)

[[10  1]
 [ 2  3]]


In [45]:
a.flat[:]

array([10,  1,  2,  3])

In [46]:
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

In [48]:
# 修改 b 会改变 a
b[0] = 10
print(a)

[[10  1]
 [ 2  3]]


In [49]:
a = array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [50]:
b[0] = 10
aa

array([[0, 2],
       [1, 3]])

In [51]:
a

array([[0, 1],
       [2, 3]])

In [52]:
b

array([10,  2,  1,  3])

atleast_xd 函数

保证数组至少有 x 维：

In [53]:
x = 1
atleast_1d(x)

array([1])

In [54]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [55]:
b

array([[1, 2, 3]])

In [56]:
c = atleast_3d(b)
c.shape

(1, 3, 1)

在Scipy库中，这些函数被用来保证输入满足一定的条件