In [13]:
%pylab
from numpy.random import rand
a = rand(3,4)
a

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


array([[ 0.389,  0.282,  0.825,  0.462],
       [ 0.555,  0.676,  0.685,  0.639],
       [ 0.306,  0.707,  0.454,  0.904]])

In [15]:
%precision 3
# Ipython magic : decimal
a

array([[ 0.389,  0.282,  0.825,  0.462],
       [ 0.555,  0.676,  0.685,  0.639],
       [ 0.306,  0.707,  0.454,  0.904]])

In [16]:
a.min()

0.282

In [17]:
a.min(axis=0)

array([ 0.306,  0.282,  0.454,  0.462])

In [18]:
a.max()

0.904

In [19]:
a.max(axis=1)

array([ 0.825,  0.685,  0.904])

In [20]:
a.argmin()

1

In [21]:
a.argmin(axis=0)

array([2, 0, 2, 0], dtype=int64)

In [22]:
a = array([[1,2,3],[4,5,6]])
a.mean()

3.500

In [23]:
a.mean(axis=-1)

array([ 2.,  5.])

In [24]:
average(a,axis=0)

array([ 2.5,  3.5,  4.5])

In [25]:
average(a,axis=0,weights=[1,2])

array([ 3.,  4.,  5.])

In [26]:
a.std(axis=1)

array([ 0.816,  0.816])

In [27]:
var(a,axis=1)

array([ 0.667,  0.667])

In [28]:
std(a,axis=1)

array([ 0.816,  0.816])

clip 方法
将数值限制在某个范围：

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

小于3的变成3，大于5的变成5。

In [31]:
a.ptp(axis=1) #计算最大值和最小值之差

array([2, 2])

In [32]:
a.ptp()

5

In [33]:
a = array([1.35,2.5,1.5])

In [34]:
a.round()

array([ 1.,  2.,  2.])

In [35]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])