In [1]:
from numpy import *

In [2]:
lst = [0,1,2,3]
a = array(lst)
a

array([0, 1, 2, 3])

In [3]:
a = array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a.shape

(4,)

In [9]:
shape(a)

(4,)

In [10]:
lst = [1,2,3,4]
shape(lst)

(4,)

In [11]:
a.size

4

In [12]:
a.nbytes

16

In [13]:
a.ndim

1

In [15]:
a.fill(-4.8)
a

array([-4, -4, -4, -4])

In [16]:
a = array([0,1,2,3])
a[0]

0

In [17]:
a[0]=10
a

array([10,  1,  2,  3])

In [18]:
a[1:-2]

array([1])