In [1]:
from numpy import *

In [2]:
lst = [0,1,2,3]
a = array(lst)
a

array([0, 1, 2, 3])

In [3]:
a = array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int32')

In [7]:
a.itemsize

4

In [8]:
a.shape

(4,)

In [9]:
shape(a)

(4,)

In [10]:
lst = [1,2,3,4]
shape(lst)

(4,)

In [11]:
a.size

4

In [12]:
a.nbytes

16

In [13]:
a.ndim

1

In [15]:
a.fill(-4.8)
a

array([-4, -4, -4, -4])

In [16]:
a = array([0,1,2,3])
a[0]

0

In [17]:
a[0]=10
a

array([10,  1,  2,  3])

In [18]:
a[1:-2]

array([1])

In [20]:
a = random.rand(10)
a

array([ 0.57442041,  0.07788677,  0.75348707,  0.54010373,  0.64546159,
        0.78366566,  0.87778269,  0.09093406,  0.25996352,  0.80413738])

In [21]:
mask = a > 0.5
a[mask]

array([ 0.57442041,  0.75348707,  0.54010373,  0.64546159,  0.78366566,
        0.87778269,  0.80413738])

In [22]:
b = arange(0,80,10)
b

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [23]:
indice = [1,2,-3]
y = b[indice]
y

array([10, 20, 50])

In [24]:
mask = array([0,1,0,1,1,0,0,0],dtype=bool)
a[mask]

C:\Users\Zishi\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 8
  from ipykernel import kernelapp as app


array([ 0.07788677,  0.54010373,  0.64546159])

In [28]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [29]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [30]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [31]:
a[:3]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [32]:
condition = array([0,1,1,0,1],dtype=bool)
a[condition]

C:\Users\Zishi\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5
  from ipykernel import kernelapp as app


array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

In [33]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [34]:
y = a[:,:,[2,-1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

In [35]:
a = array([0,12,5,20])
a >10

array([False,  True, False,  True], dtype=bool)

In [36]:
where(a > 10)

(array([1, 3], dtype=int64),)

In [37]:
indices = where(a>10)[0]
indices

array([1, 3], dtype=int64)

In [38]:
loc = where(a>10)
a[loc]

array([12, 20])

In [39]:
a = array([[0,12,5,20],[1,2,11,15]])
loc = where(a > 10)
loc

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 2, 3], dtype=int64))

In [40]:
a[loc]

array([12, 20, 11, 15])

In [42]:
rows,cols=where(a>10)
rows

array([0, 0, 1, 1], dtype=int64)

In [43]:
cols

array([1, 3, 2, 3], dtype=int64)

In [44]:
a[rows,cols]

array([12, 20, 11, 15])

In [45]:
a = arange(25)
a.shape =5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [47]:
where(a > 12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [48]:
a[where(a>12)]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])