In [1]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

In [2]:
np.ones((10,5)).shape

(10, 5)

In [3]:
np.ones((3,4,5),dtype=np.float64).strides

(160, 40, 8)

In [4]:
ints = np.ones(10, dtype=np.uint16)
floats=np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype,np.integer)

True

In [5]:
np.issubdtype(floats.dtype,np.floating)

True

In [6]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [7]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [8]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [9]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
arr=np.arange(15)
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
other_arr = np.ones((3,5))
other_arr.shape

(3, 5)

In [12]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
arr.ravel()
# Does not return a copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr.flatten()
# Always return a copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr.ravel() is arr.flatten()

False

In [17]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [20]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [21]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [25]:
from numpy.random import randn
arr = randn(5,2)
arr

array([[-0.1002, -0.5474],
       [-0.4183, -0.7975],
       [ 0.5739, -0.1238],
       [ 2.0012,  0.0923],
       [-0.1986,  1.3687]])

In [26]:
first,second,third = np.split(arr,[1,3])

In [27]:
first

array([[-0.1002, -0.5474]])

In [28]:
second

array([[-0.4183, -0.7975],
       [ 0.5739, -0.1238]])

In [29]:
third

array([[ 2.0012,  0.0923],
       [-0.1986,  1.3687]])

In [30]:
np.row_stack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
np.column_stack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [32]:
arr3 = np.array([[13,14,15],[16,17,18]])

In [33]:
to_split = np.dstack((arr1,arr2,arr3))

In [34]:
to_split

array([[[ 1,  7, 13],
        [ 2,  8, 14],
        [ 3,  9, 15]],

       [[ 4, 10, 16],
        [ 5, 11, 17],
        [ 6, 12, 18]]])

In [35]:
np.hsplit(to_split,3)

[array([[[ 1,  7, 13]],
 
        [[ 4, 10, 16]]]), array([[[ 2,  8, 14]],
 
        [[ 5, 11, 17]]]), array([[[ 3,  9, 15]],
 
        [[ 6, 12, 18]]])]

In [36]:
np.vsplit(to_split,2)

[array([[[ 1,  7, 13],
         [ 2,  8, 14],
         [ 3,  9, 15]]]), array([[[ 4, 10, 16],
         [ 5, 11, 17],
         [ 6, 12, 18]]])]

In [37]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = randn(3,2)

In [38]:
np.r_[arr1,arr2]
# equals to vstack

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [-1.2763,  1.0241],
       [ 1.4463, -0.623 ],
       [-0.2818, -1.2741]])

In [39]:
np.c_[np.r_[arr1,arr2],arr]
# same as hstack

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [-1.2763,  1.0241,  3.    ],
       [ 1.4463, -0.623 ,  4.    ],
       [-0.2818, -1.2741,  5.    ]])

In [40]:
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [41]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [42]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [43]:
arr = randn(2,2)
arr

array([[ 1.6849,  0.3021],
       [-0.6693, -1.3742]])

In [44]:
arr.repeat(2,axis=0)

array([[ 1.6849,  0.3021],
       [ 1.6849,  0.3021],
       [-0.6693, -1.3742],
       [-0.6693, -1.3742]])

In [45]:
arr.repeat(2)
# array will be flattened without axis in param

array([ 1.6849,  1.6849,  0.3021,  0.3021, -0.6693, -0.6693, -1.3742,
       -1.3742])

In [46]:
arr.repeat([2,3],axis=0)

array([[ 1.6849,  0.3021],
       [ 1.6849,  0.3021],
       [-0.6693, -1.3742],
       [-0.6693, -1.3742],
       [-0.6693, -1.3742]])

In [47]:
arr.repeat([2,3],axis=1)

array([[ 1.6849,  1.6849,  0.3021,  0.3021,  0.3021],
       [-0.6693, -0.6693, -1.3742, -1.3742, -1.3742]])

In [48]:
arr

array([[ 1.6849,  0.3021],
       [-0.6693, -1.3742]])

In [49]:
np.tile(arr,2)

array([[ 1.6849,  0.3021,  1.6849,  0.3021],
       [-0.6693, -1.3742, -0.6693, -1.3742]])

In [50]:
np.tile(arr,(2,1))
# 2*1 tile

array([[ 1.6849,  0.3021],
       [-0.6693, -1.3742],
       [ 1.6849,  0.3021],
       [-0.6693, -1.3742]])

In [51]:
np.tile(arr,(3,2))
# 3*2 tile

array([[ 1.6849,  0.3021,  1.6849,  0.3021],
       [-0.6693, -1.3742, -0.6693, -1.3742],
       [ 1.6849,  0.3021,  1.6849,  0.3021],
       [-0.6693, -1.3742, -0.6693, -1.3742],
       [ 1.6849,  0.3021,  1.6849,  0.3021],
       [-0.6693, -1.3742, -0.6693, -1.3742]])

In [52]:
arr = np.arange(10)*100
inds = [7,1,2,6]

In [53]:
arr[inds]

array([700, 100, 200, 600])

In [54]:
arr.take(inds)

array([700, 100, 200, 600])

In [55]:
arr.put(inds,42)

In [56]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [57]:
inds=[2,0,2,1]
arr = randn(2,4)

In [58]:
arr

array([[-0.3542,  1.4182, -0.1624, -1.9089],
       [ 0.1805, -0.2517,  1.8458,  0.3228]])

In [59]:
arr.take(inds,axis=1)

array([[-0.1624, -0.3542, -0.1624,  1.4182],
       [ 1.8458,  0.1805,  1.8458, -0.2517]])

In [60]:
arr = np.arange(5)

In [61]:
arr

array([0, 1, 2, 3, 4])

In [62]:
arr*4

array([ 0,  4,  8, 12, 16])

In [63]:
arr = randn(4,3)
arr.mean(0)

array([-0.175 , -0.3163,  0.0672])

In [64]:
demeaned = arr - arr.mean(0)

In [65]:
demeaned

array([[-0.6671,  0.1343,  0.339 ],
       [ 0.3651,  0.1802, -0.0486],
       [ 0.2579, -1.0284, -0.2107],
       [ 0.0441,  0.7139, -0.0796]])

In [66]:
demeaned.mean(0)

array([ -2.0817e-17,   0.0000e+00,   0.0000e+00])

In [67]:
arr

array([[-0.8421, -0.182 ,  0.4062],
       [ 0.1901, -0.1361,  0.0186],
       [ 0.0829, -1.3448, -0.1435],
       [-0.1309,  0.3975, -0.0124]])

In [68]:
row_means = arr.mean(1)

In [69]:
row_means

array([-0.206 ,  0.0242, -0.4685,  0.0847])

In [70]:
row_means.reshape((4,1))

array([[-0.206 ],
       [ 0.0242],
       [-0.4685],
       [ 0.0847]])

In [71]:
demeaned=arr - row_means.reshape((4,1))

In [72]:
demeaned.mean(1)

array([  0.0000e+00,  -1.1565e-18,   3.7007e-17,  -9.2519e-18])

In [73]:
arr = np.zeros((4,4))
arr_3d = arr[:,np.newaxis,:]

In [74]:
arr_3d.shape

(4, 1, 4)

In [75]:
arr_1d = np.random.normal(size=3)

In [76]:
arr_1d[:,np.newaxis]

array([[ 1.1541],
       [-0.2577],
       [-0.3998]])

In [77]:
arr_1d[np.newaxis,:]

array([[ 1.1541, -0.2577, -0.3998]])

In [78]:
arr = randn(3,4,5)
depth_means = arr.mean(2)
depth_means

array([[ 0.0116, -0.5758,  0.1663,  0.6829],
       [-0.0465, -0.5543, -0.1419, -0.1091],
       [ 0.2009, -0.2328, -0.0036,  0.3471]])

In [79]:
demeaned = arr - depth_means[:,:,np.newaxis]
demeaned.mean(2)

array([[ -1.1102e-17,   4.4409e-17,   2.2204e-17,   6.6613e-17],
       [  4.4409e-17,   0.0000e+00,   0.0000e+00,   4.4409e-17],
       [  0.0000e+00,   0.0000e+00,   2.2204e-17,   1.1102e-17]])

In [80]:
def demean_axis(arr,axis=0):
    means = arr.mean(axis)
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [81]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [82]:
col = np.array([1.28,-0.42,0.44,1.6])
arr[:] = col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [83]:
col[:,np.newaxis] == col.reshape(-1,1)

array([[ True],
       [ True],
       [ True],
       [ True]], dtype=bool)

In [84]:
arr[:2] = [[-1.37],[0.509]]

In [85]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [86]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [87]:
arr.sum()

45

In [88]:
arr = randn(5,5)

In [89]:
arr[::2].sort(1)

In [90]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [91]:
np.logical_and.reduce(arr[:,:-1]<arr[:,1:],axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [92]:
arr = np.arange(15).reshape((3,5))

In [93]:
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [94]:
arr = np.arange(3).repeat([1,2,2])
arr

array([0, 1, 1, 2, 2])

In [95]:
np.multiply.outer(arr,np.arange(5))
# vertically arr * each number in np.arange(5) then output a column per product

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [96]:
result = np.subtract.outer(randn(3,4),randn(5))
result.shape

(3, 4, 5)

In [97]:
arr = np.arange(10)
np.add.reduceat(arr,[0,5,8])
# cumsum at [0:5],[5:8] and [8:]

array([10, 18, 17], dtype=int32)

In [98]:
arr = np.multiply.outer(np.arange(4),np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [99]:
np.add.reduceat(arr,[0,2,4],axis=1)
# cumsum at [0:2],[2:4],[4:] on axis =1

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

In [100]:
np.add.reduceat(arr,[0,2,3],axis=0)
# axis 0 = column, axis 1 = row

array([[ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]], dtype=int32)

In [101]:
def add_elements(x,y):
    return x+y

In [102]:
add_them = np.frompyfunc(add_elements,2,1)

In [103]:
add_them(np.arange(8),np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [104]:
add_them = np.vectorize(add_elements,otypes=[np.float64])
add_them(np.arange(8),np.arange(8))

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [105]:
arr = randn(10000)
%timeit add_them(arr,arr)
%timeit np.add(arr,arr)

1.91 ms ± 15.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
4.09 µs ± 444 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [106]:
dtype =[('x',np.float64),('y',np.int32)]

In [107]:
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)
sarr

array([( 1.5   ,  6), ( 3.1416, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [108]:
sarr[0]

( 1.5, 6)

In [109]:
sarr[0]['y']

6

In [110]:
sarr['x']

array([ 1.5   ,  3.1416])

In [111]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [112]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [113]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [114]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([( 1.,  2.), ( 3.,  4.)],
      dtype=[('a', '<f8'), ('b', '<f4')])

In [115]:
data['y']

array([5, 6])

In [116]:
data['x']['a']

array([ 1.,  3.])

In [117]:
arr = randn(3,5)
arr

array([[-1.5313,  1.0117,  0.2006,  0.1902,  0.8601],
       [ 1.0919,  0.4831,  0.8581, -0.1735, -0.1592],
       [ 0.0383, -0.0201, -0.3161,  1.3158,  0.6483]])

In [118]:
arr[:,0].sort()

In [119]:
arr

array([[-1.5313,  1.0117,  0.2006,  0.1902,  0.8601],
       [ 0.0383,  0.4831,  0.8581, -0.1735, -0.1592],
       [ 1.0919, -0.0201, -0.3161,  1.3158,  0.6483]])

In [120]:
arr = randn(5)
arr

array([ 1.0084, -1.1677, -1.1938, -0.6325,  1.1452])

In [121]:
np.sort(arr)

array([-1.1938, -1.1677, -0.6325,  1.0084,  1.1452])

In [122]:
arr

array([ 1.0084, -1.1677, -1.1938, -0.6325,  1.1452])

In [123]:
arr = randn(3,5)
arr

array([[-0.3993,  0.4959, -0.9253,  1.2396, -1.2793],
       [-0.2223,  0.983 , -0.1654, -0.4662, -1.3766],
       [-0.1452, -0.8388, -0.0072, -1.1227, -0.1489]])

In [124]:
arr.sort(axis=1)

In [125]:
arr

array([[-1.2793, -0.9253, -0.3993,  0.4959,  1.2396],
       [-1.3766, -0.4662, -0.2223, -0.1654,  0.983 ],
       [-1.1227, -0.8388, -0.1489, -0.1452, -0.0072]])

In [126]:
arr[:,::-1]

array([[ 1.2396,  0.4959, -0.3993, -0.9253, -1.2793],
       [ 0.983 , -0.1654, -0.2223, -0.4662, -1.3766],
       [-0.0072, -0.1452, -0.1489, -0.8388, -1.1227]])

In [127]:
values = np.array([5,0,1,3,2])
indexer = values.argsort()

In [128]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [129]:
values[indexer]

array([0, 1, 2, 3, 5])

In [130]:
arr = randn(3,5)
arr[0] = values

In [131]:
arr

array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [-0.2905, -0.379 ,  0.3129, -0.2478,  0.8733],
       [ 0.9214,  1.2067,  0.7236,  1.4892, -0.6706]])

In [132]:
arr[:,arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [-0.379 ,  0.3129,  0.8733, -0.2478, -0.2905],
       [ 1.2067,  0.7236, -0.6706,  1.4892,  0.9214]])

In [133]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [134]:
sorter = np.lexsort((first_name,last_name))

In [135]:
[k+' '+v for k,v in zip(last_name[sorter],first_name[sorter])]

['Arnold Jane', 'Arnold Steve', 'Jones Bill', 'Jones Bob', 'Walters Barbara']

In [136]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])

In [137]:
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [138]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [139]:
key.take(indexer)

array([1, 1, 1, 2, 2])

In [140]:
arr = np.array([0,1,7,12,15])
arr.searchsorted(9)

3

In [141]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5], dtype=int64)

In [142]:
arr = np.array([0,1]).repeat([3,4])
arr

array([0, 0, 0, 1, 1, 1, 1])

In [143]:
arr.searchsorted([0,1])

array([0, 3], dtype=int64)

In [144]:
arr.searchsorted([0,1],side='right')

array([3, 7], dtype=int64)

In [145]:
data = np.floor(np.random.uniform(0,10000, size=50))

In [146]:
bins = np.array([0,100,1000,5000,10000])

In [147]:
data

array([ 8583.,  3470.,  8480.,  5020.,  5841.,  9676.,  5723.,  9594.,
         759.,  2332.,  9262.,   973.,  5528.,  9846.,  3419.,  9057.,
        1108.,  7129.,  5638.,  1746.,  4641.,  2377.,  4518.,  2177.,
        9028.,  5978.,  8845.,  5977.,  8194.,  3121.,  9259.,  3881.,
        5700.,  4362.,  7581.,  2352.,  7965.,  8368.,  9702.,  9148.,
        4533.,  8040.,  2704.,  9357.,   623.,  6744.,  4753.,  7370.,
         983.,  5605.])

In [148]:
labels = bins.searchsorted(data)
labels

array([4, 3, 4, 4, 4, 4, 4, 4, 2, 3, 4, 2, 4, 4, 3, 4, 3, 4, 4, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 4, 3, 4, 4, 4, 4, 3, 4, 3, 4, 2, 4,
       3, 4, 2, 4], dtype=int64)

In [149]:
Series(data).groupby(labels).mean()

2     834.500000
3    3218.375000
4    7741.266667
dtype: float64

In [150]:
np.digitize(data,bins)

array([4, 3, 4, 4, 4, 4, 4, 4, 2, 3, 4, 2, 4, 4, 3, 4, 3, 4, 4, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 3, 4, 3, 4, 3, 4, 3, 4, 4, 4, 4, 3, 4, 3, 4, 2, 4,
       3, 4, 2, 4], dtype=int64)

In [151]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [152]:
X[:,0]

array([ 8.8277,  3.8222, -1.1428,  2.0441])

In [153]:
y = X[:,:1]
y

array([[ 8.8277],
       [ 3.8222],
       [-1.1428],
       [ 2.0441]])

In [154]:
np.dot(y.T,np.dot(X,y))

array([[ 1195.468]])

In [155]:
Xm=np.mat(X)
Xm

matrix([[ 8.8277,  3.8222, -1.1428,  2.0441],
        [ 3.8222,  6.7527,  0.8391,  2.0829],
        [-1.1428,  0.8391,  5.0169,  0.7957],
        [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [156]:
ym = Xm[:,0]
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [157]:
ym.T*Xm*ym

matrix([[ 1195.468]])

In [158]:
Xm.I*X

matrix([[  1.0000e+00,   0.0000e+00,  -5.5511e-17,   5.5511e-17],
        [ -1.1102e-16,   1.0000e+00,   2.7756e-17,  -5.5511e-17],
        [  1.1102e-16,   0.0000e+00,   1.0000e+00,   0.0000e+00],
        [ -5.5511e-17,  -5.5511e-17,   2.7756e-17,   1.0000e+00]])

In [159]:
np.asarray(Xm.I*X)
# transform back to array

array([[  1.0000e+00,   0.0000e+00,  -5.5511e-17,   5.5511e-17],
       [ -1.1102e-16,   1.0000e+00,   2.7756e-17,  -5.5511e-17],
       [  1.1102e-16,   0.0000e+00,   1.0000e+00,   0.0000e+00],
       [ -5.5511e-17,  -5.5511e-17,   2.7756e-17,   1.0000e+00]])

In [160]:
mmap = np.memmap('mymmap',dtype='float64',mode='w+',shape=(10000,10000))
mmap

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [161]:
section = mmap[:5]

In [162]:
section[:] = np.random.randn(5,10000)

In [163]:
section

memmap([[ 0.6159, -0.1094, -0.1724, ..., -0.0797, -0.81  , -0.4499],
        [ 0.0352,  0.2569,  0.4895, ..., -1.4884,  1.6025, -1.4035],
        [ 0.2147, -1.2015, -0.9268, ...,  0.9894,  1.1224, -0.8254],
        [-0.4502, -1.3013,  1.6184, ..., -1.1448, -0.8311,  0.3342],
        [-0.469 , -0.4259,  1.8478, ..., -0.3402, -0.104 ,  1.0024]])

In [164]:
section.shape

(5, 10000)

In [165]:
mmap.flush()

In [166]:
mmap

memmap([[ 0.6159, -0.1094, -0.1724, ..., -0.0797, -0.81  , -0.4499],
        [ 0.0352,  0.2569,  0.4895, ..., -1.4884,  1.6025, -1.4035],
        [ 0.2147, -1.2015, -0.9268, ...,  0.9894,  1.1224, -0.8254],
        ..., 
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [167]:
del mmap

In [169]:
mmap = np.memmap('mymmap',dtype='float64',shape=(10000,10000))

In [170]:
mmap

memmap([[ 0.6159, -0.1094, -0.1724, ..., -0.0797, -0.81  , -0.4499],
        [ 0.0352,  0.2569,  0.4895, ..., -1.4884,  1.6025, -1.4035],
        [ 0.2147, -1.2015, -0.9268, ...,  0.9894,  1.1224, -0.8254],
        ..., 
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]])

In [171]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError: 
        return False

In [172]:
isiterable('a string')

True

In [173]:
isiterable([1,2,3])

True

In [174]:
isiterable(5)

False