In [1]:
from __future__ import division
from numpy.random import randn
from pandas import Series
import numpy as np
np.set_printoptions(precision=4)
import sys

In [2]:
np.ones((10,5)).shape

(10, 5)

In [3]:
np.ones((3,4,5),dtype=np.float64).strides

(160, 40, 8)

In [6]:
ints = np.ones(10, dtype=np.uint16)
floats=np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype,np.integer)

True

In [8]:
np.issubdtype(floats.dtype,np.floating)

True

In [7]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [9]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr=np.arange(15)
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
other_arr = np.ones((3,5))
other_arr.shape

(3, 5)

In [14]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
arr.ravel()
# Does not return a copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr.flatten()
# Always return a copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr.ravel() is arr.flatten()

False

In [22]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [25]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [28]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [33]:
from numpy.random import randn
arr = randn(5,2)
arr

array([[-0.1303, -1.5359],
       [ 0.9522, -0.44  ],
       [ 1.3793,  0.553 ],
       [ 0.1026,  1.1911],
       [-2.4607,  2.0385]])

In [34]:
first,second,third = np.split(arr,[1,3])

In [35]:
first

array([[-0.1303, -1.5359]])

In [36]:
second

array([[ 0.9522, -0.44  ],
       [ 1.3793,  0.553 ]])

In [37]:
third

array([[ 0.1026,  1.1911],
       [-2.4607,  2.0385]])

In [41]:
np.row_stack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.column_stack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [44]:
arr3 = np.array([[13,14,15],[16,17,18]])

In [46]:
to_split = np.dstack((arr1,arr2,arr3))

In [47]:
to_split

array([[[ 1,  7, 13],
        [ 2,  8, 14],
        [ 3,  9, 15]],

       [[ 4, 10, 16],
        [ 5, 11, 17],
        [ 6, 12, 18]]])

In [52]:
np.hsplit(to_split,3)

[array([[[ 1,  7, 13]],
 
        [[ 4, 10, 16]]]), array([[[ 2,  8, 14]],
 
        [[ 5, 11, 17]]]), array([[[ 3,  9, 15]],
 
        [[ 6, 12, 18]]])]

In [54]:
np.vsplit(to_split,2)

[array([[[ 1,  7, 13],
         [ 2,  8, 14],
         [ 3,  9, 15]]]), array([[[ 4, 10, 16],
         [ 5, 11, 17],
         [ 6, 12, 18]]])]

In [55]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = randn(3,2)

In [56]:
np.r_[arr1,arr2]
# equals to vstack

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [ 1.0267,  0.6652],
       [-0.7124, -0.1236],
       [ 0.5092,  0.9398]])

In [57]:
np.c_[np.r_[arr1,arr2],arr]
# same as hstack

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [ 1.0267,  0.6652,  3.    ],
       [-0.7124, -0.1236,  4.    ],
       [ 0.5092,  0.9398,  5.    ]])

In [60]:
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [61]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [63]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [64]:
arr = randn(2,2)
arr

array([[-1.0174, -3.5104],
       [-0.2847,  0.3771]])

In [65]:
arr.repeat(2,axis=0)

array([[-1.0174, -3.5104],
       [-1.0174, -3.5104],
       [-0.2847,  0.3771],
       [-0.2847,  0.3771]])

In [66]:
arr.repeat(2)
# array will be flattened without axis in param

array([-1.0174, -1.0174, -3.5104, -3.5104, -0.2847, -0.2847,  0.3771,
        0.3771])

In [67]:
arr.repeat([2,3],axis=0)

array([[-1.0174, -3.5104],
       [-1.0174, -3.5104],
       [-0.2847,  0.3771],
       [-0.2847,  0.3771],
       [-0.2847,  0.3771]])

In [68]:
arr.repeat([2,3],axis=1)

array([[-1.0174, -1.0174, -3.5104, -3.5104, -3.5104],
       [-0.2847, -0.2847,  0.3771,  0.3771,  0.3771]])

In [69]:
arr

array([[-1.0174, -3.5104],
       [-0.2847,  0.3771]])

In [70]:
np.tile(arr,2)

array([[-1.0174, -3.5104, -1.0174, -3.5104],
       [-0.2847,  0.3771, -0.2847,  0.3771]])

In [71]:
np.tile(arr,(2,1))
# 2*1 tile

array([[-1.0174, -3.5104],
       [-0.2847,  0.3771],
       [-1.0174, -3.5104],
       [-0.2847,  0.3771]])

In [72]:
np.tile(arr,(3,2))
# 3*2 tile

array([[-1.0174, -3.5104, -1.0174, -3.5104],
       [-0.2847,  0.3771, -0.2847,  0.3771],
       [-1.0174, -3.5104, -1.0174, -3.5104],
       [-0.2847,  0.3771, -0.2847,  0.3771],
       [-1.0174, -3.5104, -1.0174, -3.5104],
       [-0.2847,  0.3771, -0.2847,  0.3771]])

In [73]:
arr = np.arange(10)*100
inds = [7,1,2,6]

In [74]:
arr[inds]

array([700, 100, 200, 600])

In [75]:
arr.take(inds)

array([700, 100, 200, 600])

In [76]:
arr.put(inds,42)

In [77]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [78]:
inds=[2,0,2,1]
arr = randn(2,4)

In [79]:
arr

array([[-0.0769,  0.7468,  1.1816, -0.1296],
       [ 0.0382,  1.2475,  1.7754,  0.3867]])

In [80]:
arr.take(inds,axis=1)

array([[ 1.1816, -0.0769,  1.1816,  0.7468],
       [ 1.7754,  0.0382,  1.7754,  1.2475]])

In [81]:
arr = np.arange(5)

In [82]:
arr

array([0, 1, 2, 3, 4])

In [83]:
arr*4

array([ 0,  4,  8, 12, 16])

In [84]:
arr = randn(4,3)
arr.mean(0)

array([ 0.4112, -0.2181, -0.4938])

In [85]:
demeaned = arr - arr.mean(0)

In [86]:
demeaned

array([[-0.3442, -0.3915, -0.1693],
       [-1.1387,  0.9172, -0.3498],
       [ 0.546 ,  0.3232, -0.5041],
       [ 0.9369, -0.8489,  1.0232]])

In [87]:
demeaned.mean(0)

array([ 0.,  0.,  0.])

In [88]:
arr

array([[ 0.067 , -0.6095, -0.6631],
       [-0.7275,  0.6991, -0.8436],
       [ 0.9572,  0.1051, -0.9979],
       [ 1.3481, -1.067 ,  0.5294]])

In [89]:
row_means = arr.mean(1)

In [90]:
row_means

array([-0.4019, -0.2907,  0.0215,  0.2702])

In [91]:
row_means.reshape((4,1))

array([[-0.4019],
       [-0.2907],
       [ 0.0215],
       [ 0.2702]])

In [92]:
demeaned=arr - row_means.reshape((4,1))

In [93]:
demeaned.mean(1)

array([  1.8504e-17,  -7.4015e-17,   0.0000e+00,   1.8504e-17])

In [94]:
arr = np.zeros((4,4))
arr_3d = arr[:,np.newaxis,:]

In [95]:
arr_3d.shape

(4, 1, 4)

In [96]:
arr_1d = np.random.normal(size=3)

In [97]:
arr_1d[:,np.newaxis]

array([[ 0.714 ],
       [-0.4743],
       [-1.3068]])

In [98]:
arr_1d[np.newaxis,:]

array([[ 0.714 , -0.4743, -1.3068]])

In [99]:
arr = randn(3,4,5)
depth_means = arr.mean(2)
depth_means

array([[ 0.2825,  0.2318,  0.2502, -0.2798],
       [ 0.1893,  0.0013,  0.0997, -0.0946],
       [ 0.9303,  0.2882, -0.3149, -0.1151]])

In [101]:
demeaned = arr - depth_means[:,:,np.newaxis]
demeaned.mean(2)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [102]:
def demean_axis(arr,axis=0):
    means = arr.mean(axis)
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [103]:
arr = np.zeros((4,3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [104]:
col = np.array([1.28,-0.42,0.44,1.6])
arr[:] = col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [108]:
col[:,np.newaxis] == col.reshape(-1,1)

array([[ True],
       [ True],
       [ True],
       [ True]], dtype=bool)

In [109]:
arr[:2] = [[-1.37],[0.509]]

In [110]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [111]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [112]:
arr.sum()

45

In [113]:
arr = randn(5,5)

In [114]:
arr[::2].sort(1)

In [115]:
arr[:,:-1] < arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [116]:
np.logical_and.reduce(arr[:,:-1]<arr[:,1:],axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [117]:
arr = np.arange(15).reshape((3,5))

In [118]:
np.add.accumulate(arr,axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [119]:
arr = np.arange(3).repeat([1,2,2])
arr

array([0, 1, 1, 2, 2])

In [120]:
np.multiply.outer(arr,np.arange(5))
# vertically arr * each number in np.arange(5) then output a column per product

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [121]:
result = np.subtract.outer(randn(3,4),randn(5))
result.shape

(3, 4, 5)

In [122]:
arr = np.arange(10)
np.add.reduceat(arr,[0,5,8])
# cumsum at [0:5],[5:8] and [8:]

array([10, 18, 17], dtype=int32)

In [123]:
arr = np.multiply.outer(np.arange(4),np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [124]:
np.add.reduceat(arr,[0,2,4],axis=1)
# cumsum at [0:2],[2:4],[4:] on axis =1

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

In [126]:
np.add.reduceat(arr,[0,2,3],axis=0)
# axis 0 = column, axis 1 = row

array([[ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]], dtype=int32)

In [127]:
def add_elements(x,y):
    return x+y

In [128]:
add_them = np.frompyfunc(add_elements,2,1)

In [130]:
add_them(np.arange(8),np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [131]:
add_them = np.vectorize(add_elements,otypes=[np.float64])
add_them(np.arange(8),np.arange(8))

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [132]:
arr = randn(10000)
%timeit add_them(arr,arr)
%timeit np.add(arr,arr)

1.93 ms ± 45.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
3.76 µs ± 59.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [133]:
dtype =[('x',np.float64),('y',np.int32)]

In [134]:
sarr = np.array([(1.5,6),(np.pi,-2)],dtype=dtype)
sarr

array([( 1.5   ,  6), ( 3.1416, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [135]:
sarr[0]

( 1.5, 6)

In [137]:
sarr[0]['y']

6

In [138]:
sarr['x']

array([ 1.5   ,  3.1416])

In [139]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [140]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [141]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [142]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([( 1.,  2.), ( 3.,  4.)],
      dtype=[('a', '<f8'), ('b', '<f4')])

In [143]:
data['y']

array([5, 6])

In [144]:
data['x']['a']

array([ 1.,  3.])

In [145]:
arr = randn(3,5)
arr

array([[ 0.0881,  0.3669,  0.0321, -0.085 , -2.1085],
       [-0.549 ,  0.489 , -1.8534, -0.1645,  0.5287],
       [ 1.3437, -0.1519, -0.0774,  0.2609, -0.6278]])

In [146]:
arr[:,0].sort()

In [147]:
arr

array([[-0.549 ,  0.3669,  0.0321, -0.085 , -2.1085],
       [ 0.0881,  0.489 , -1.8534, -0.1645,  0.5287],
       [ 1.3437, -0.1519, -0.0774,  0.2609, -0.6278]])

In [148]:
arr = randn(5)
arr

array([ 0.9409, -0.3425,  0.1587, -1.3098, -0.47  ])

In [149]:
np.sort(arr)

array([-1.3098, -0.47  , -0.3425,  0.1587,  0.9409])

In [150]:
arr

array([ 0.9409, -0.3425,  0.1587, -1.3098, -0.47  ])

In [151]:
arr = randn(3,5)
arr

array([[ 0.0775,  0.4882,  0.4487, -0.0761,  0.4512],
       [ 0.386 ,  0.0627, -0.522 , -0.7042,  0.4204],
       [ 0.4268, -0.8524,  0.1246,  1.1954, -0.8194]])

In [152]:
arr.sort(axis=1)

In [153]:
arr

array([[-0.0761,  0.0775,  0.4487,  0.4512,  0.4882],
       [-0.7042, -0.522 ,  0.0627,  0.386 ,  0.4204],
       [-0.8524, -0.8194,  0.1246,  0.4268,  1.1954]])

In [154]:
arr[:,::-1]

array([[ 0.4882,  0.4512,  0.4487,  0.0775, -0.0761],
       [ 0.4204,  0.386 ,  0.0627, -0.522 , -0.7042],
       [ 1.1954,  0.4268,  0.1246, -0.8194, -0.8524]])

In [155]:
values = np.array([5,0,1,3,2])
indexer = values.argsort()

In [156]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [157]:
values[indexer]

array([0, 1, 2, 3, 5])

In [158]:
arr = randn(3,5)
arr[0] = values

In [159]:
arr

array([[ 5.    ,  0.    ,  1.    ,  3.    ,  2.    ],
       [-0.089 , -0.0583,  1.4142, -0.7072,  1.8553],
       [-0.5583, -1.7187, -0.4401, -0.3217,  2.2716]])

In [160]:
arr[:,arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [-0.0583,  1.4142,  1.8553, -0.7072, -0.089 ],
       [-1.7187, -0.4401,  2.2716, -0.3217, -0.5583]])

In [161]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [162]:
sorter = np.lexsort((first_name,last_name))

In [165]:
[k+','+v for k,v in zip(last_name[sorter],first_name[sorter])]

['Arnold,Jane', 'Arnold,Steve', 'Jones,Bill', 'Jones,Bob', 'Walters,Barbara']

In [166]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])

In [167]:
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [168]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [169]:
key.take(indexer)

array([1, 1, 1, 2, 2])

In [171]:
arr = np.array([0,1,7,12,15])
arr.searchsorted(9)

3

In [172]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5], dtype=int64)

In [173]:
arr = np.array([0,1]).repeat([3,4])
arr

array([0, 0, 0, 1, 1, 1, 1])

In [174]:
arr.searchsorted([0,1])

array([0, 3], dtype=int64)

In [175]:
arr.searchsorted([0,1],side='right')

array([3, 7], dtype=int64)

In [176]:
data = np.floor(np.random.uniform(0,10000, size=50))

In [177]:
bins = np.array([0,100,1000,5000,10000])

In [178]:
data

array([ 4475.,  6146.,  8662.,  2282.,  9872.,   651.,   485.,  7401.,
        5998.,  6488.,   897.,  2696.,  7516.,  9181.,   156.,  3731.,
        1266.,  7047.,  3990.,  3038.,  7978.,  4922.,  3724.,  7098.,
        5419.,  8143.,  3021.,  6554.,  2948.,  9046.,  5376.,  3708.,
        2711.,  7567.,  4424.,  4916.,  6168.,  7287.,  9584.,  5167.,
        8658.,  6806.,  2733.,  7087.,  5309.,  2333.,  4096.,  8567.,
        1453.,   624.])

In [179]:
labels = bins.searchsorted(data)
labels

array([3, 4, 4, 3, 4, 2, 2, 4, 4, 4, 2, 3, 4, 4, 2, 3, 3, 4, 3, 3, 4, 3, 3,
       4, 4, 4, 3, 4, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 3,
       3, 4, 3, 2], dtype=int64)

In [180]:
Series(data).groupby(labels).mean()

2     562.600000
3    3287.736842
4    7312.500000
dtype: float64

In [181]:
np.digitize(data,bins)

array([3, 4, 4, 3, 4, 2, 2, 4, 4, 4, 2, 3, 4, 4, 2, 3, 3, 4, 3, 3, 4, 3, 3,
       4, 4, 4, 3, 4, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 3,
       3, 4, 3, 2], dtype=int64)

In [182]:
X =  np.array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
               [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
               [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
               [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [183]:
X[:,0]

array([ 8.8277,  3.8222, -1.1428,  2.0441])

In [184]:
y = X[:,:1]
y

array([[ 8.8277],
       [ 3.8222],
       [-1.1428],
       [ 2.0441]])

In [185]:
np.dot(y.T,np.dot(X,y))

array([[ 1195.468]])

In [189]:
Xm=np.mat(X)
Xm

matrix([[ 8.8277,  3.8222, -1.1428,  2.0441],
        [ 3.8222,  6.7527,  0.8391,  2.0829],
        [-1.1428,  0.8391,  5.0169,  0.7957],
        [ 2.0441,  2.0829,  0.7957,  6.241 ]])

In [191]:
ym = Xm[:,0]
ym

matrix([[ 8.8277],
        [ 3.8222],
        [-1.1428],
        [ 2.0441]])

In [192]:
ym.T*Xm*ym

matrix([[ 1195.468]])

In [193]:
Xm.I*X

matrix([[  1.0000e+00,   0.0000e+00,  -5.5511e-17,   5.5511e-17],
        [ -1.1102e-16,   1.0000e+00,   2.7756e-17,  -5.5511e-17],
        [  1.1102e-16,   0.0000e+00,   1.0000e+00,   0.0000e+00],
        [ -5.5511e-17,  -5.5511e-17,   2.7756e-17,   1.0000e+00]])

In [194]:
np.asarray(Xm.I*X)
# transform back to array

array([[  1.0000e+00,   0.0000e+00,  -5.5511e-17,   5.5511e-17],
       [ -1.1102e-16,   1.0000e+00,   2.7756e-17,  -5.5511e-17],
       [  1.1102e-16,   0.0000e+00,   1.0000e+00,   0.0000e+00],
       [ -5.5511e-17,  -5.5511e-17,   2.7756e-17,   1.0000e+00]])